### ISSUE TITLE
Holy shit! Love it! Beautiful App guys ;-D Consider adding an escapeHatch!

### ISSUE THREAD

**Issue by GriffGreen** [DecentLabs/chari#3]
Love the work here :-D thank you for taking this on! We built something similar (but never really put a front end to it). It was a long time ago, on an old solidity version and an old version of the Giveth DApp but I figure you might want to see it: 

https://github.com/Giveth/fund-forwarder/blob/master/contracts/FundForwarder.sol

What I really want to encourage is a solution to the edge case for potential failures of kind benefactors that maybe think they can just send tokens to the address, and then they would be stuck in the contracts.

It is best practice to create an escapeHatch as a safety net in these edge case scenarios...

This is what we use (may need to be updated to the newest solidity version:

https://github.com/Giveth/common-contract-deps/blob/master/contracts/Escapable.sol

I can't tell you how often this happens... It happens more with people that feel comfortable with ETH financially, but not necessarily are comfortably technically! Even in Moloch, there is 100 W-ETH stuck forever because of the lack of an escapehatch...

You do have an upgradeable contract, so that might be able to work out, but it would be a bit of a hassle. 

My 2 wei! 

Much love,
Griff

**Comment by phraktle** [comment]
Hi @GriffGreen,

Thanks for your support and taking the time for feedback!

We have designed the contracts so that any ERC20 token or ETH sent at any time can be transferred to the recipient address, see the [`disburse`](https://github.com/DecentLabs/chari/blob/master/shared/contracts/Fundraiser.sol#L50) function. So the charity can always retrieve funds, even if they were sent in an unexpected token.
